# Generated by Django 3.0.6 on 2020-05-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Актив', max_length=200, unique=True)),
                ('amount', models.FloatField(help_text='Колличество денег')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Трата', max_length=200, unique=True)),
                ('amount', models.FloatField(help_text='Колличество потраченных денег')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='money.Asset')),
            ],
        ),
    ]
