# Generated by Django 3.0.6 on 2020-05-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория трат', max_length=200, unique=True)),
                ('amount', models.FloatField(help_text='Колличество денег')),
            ],
        ),
        migrations.RemoveField(
            model_name='spending',
            name='source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.ProtectedError, to='money.SpendingCategory'),
            preserve_default=False,
        ),
    ]
