# Generated by Django 3.0.6 on 2020-05-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20200516_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Хранилище денег', max_length=200, unique=True)),
                ('amount', models.FloatField(help_text='Колличество денег')),
            ],
        ),
        migrations.RemoveField(
            model_name='spending',
            name='category',
        ),
        migrations.DeleteModel(
            name='SpendingCategory',
        ),
        migrations.AddField(
            model_name='spending',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='money.Source'),
            preserve_default=False,
        ),
    ]
