# Generated by Django 3.0.6 on 2020-05-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Перевод', max_length=200)),
                ('amount', models.FloatField(help_text='Сумма')),
                ('asset_from', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='asset_from', to='money.Asset')),
                ('asset_to', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='asset_to', to='money.Asset')),
            ],
        ),
    ]
