# Generated by Django 3.0.6 on 2020-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
