# Generated by Django 3.0.6 on 2020-07-13 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_spending_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
