# Generated by Django 3.0.6 on 2020-07-13 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20200713_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='money.Asset', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Трата'),
        ),
    ]
