# Generated by Django 3.0.6 on 2020-07-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20200713_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='asset_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='asset_from', to='money.Asset', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='asset_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='asset_to', to='money.Asset', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Перевод'),
        ),
    ]
