# Generated by Django 3.0.6 on 2020-07-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20200721_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.SpendingCategory', verbose_name='Категория'),
        ),
    ]
