# Generated by Django 3.0.6 on 2020-07-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20200728_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Department', verbose_name='Отдел'),
        ),
    ]
