# Generated by Django 3.0.6 on 2020-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_spending_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Актив'),
        ),
    ]
