# Generated by Django 3.0.6 on 2020-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_asset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
