# Generated by Django 3.0.6 on 2020-09-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0014_auto_20200829_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Учетный период')),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Period', verbose_name='Учетный период'),
        ),
    ]
