# Generated by Django 3.0.6 on 2020-09-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_auto_20200901_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-id']},
        ),
    ]
