# Generated by Django 3.0.6 on 2020-09-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0016_auto_20200911_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Period', verbose_name='Учетный период'),
        ),
    ]
