# Generated by Django 3.0.6 on 2021-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0017_transfer_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
    ]
