# Generated by Django 3.2.12 on 2022-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0018_auto_20210124_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Константа')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
            ],
        ),
    ]
