# Generated by Django 3.0.6 on 2020-07-24 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('money', '0007_auto_20200721_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование ингредиента')),
                ('purchase_price', models.FloatField(verbose_name='Цена покупки')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование категории', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Накладная')),
                ('created_at', models.DateField(blank=True, default=datetime.date(2020, 7, 24), null=True, verbose_name='Создана')),
                ('paid', models.FloatField(blank=True, default=0, null=True, verbose_name='Оплачено')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Asset', verbose_name='Источник')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='production.Ingredient')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='production.IngredientInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='production.IngredientCategory', verbose_name='Категория'),
        ),
    ]
