# Generated by Django 3.0.6 on 2020-07-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200724_0950'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сomplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='production.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='goods.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Proportion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='production.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='goods.Product')),
            ],
        ),
    ]
