# Generated by Django 3.0.6 on 2020-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_proportion_сomplement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proportion',
            old_name='percentage',
            new_name='quantity',
        ),
        migrations.DeleteModel(
            name='Сomplement',
        ),
    ]
