# Generated by Django 3.0.6 on 2020-07-25 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200725_1432'),
        ('production', '0003_auto_20200724_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinvoice',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 25), null=True, verbose_name='Создана'),
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(blank=True, default=datetime.date(2020, 7, 25), null=True, verbose_name='Создана')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='goods.Product')),
            ],
        ),
    ]
