# Generated by Django 3.0.6 on 2020-07-27 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200725_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientinvoice',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 27), null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 27), null=True, verbose_name='Создана'),
        ),
    ]
