# Generated by Django 3.0.6 on 2020-08-05 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20200803_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinvoice',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 5), null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 5), null=True, verbose_name='Создана'),
        ),
    ]
