# Generated by Django 3.0.6 on 2020-08-06 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20200806_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinvoice',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Создана'),
        ),
    ]
