# Generated by Django 3.0.6 on 2021-01-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20200911_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturing',
            options={'ordering': ['-created_at']},
        ),
    ]
