# Generated by Django 3.0.6 on 2020-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_sale_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'brand', 'created_at']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(help_text='Наименование накладной', max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
