# Generated by Django 3.0.6 on 2020-07-13 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200712_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(help_text='Наименование накладной', max_length=200, verbose_name='Накладная'),
        ),
    ]
