# Generated by Django 3.0.6 on 2020-07-13 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20200713_1648'),
        ('goods', '0006_auto_20200713_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Asset', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Накладная'),
        ),
    ]
