# Generated by Django 3.0.6 on 2020-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20200731_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=-1000, verbose_name='Максимальное Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=-1000, verbose_name='Минимальное Количество'),
        ),
    ]
