# Generated by Django 3.0.6 on 2020-08-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200731_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 1), null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(blank=True, default=-1000, verbose_name='Максимальное Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=-1000, verbose_name='Минимальное Количество'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 1), null=True),
        ),
    ]
