# Generated by Django 3.0.6 on 2020-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20200812_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Накладная'),
        ),
    ]
