# Generated by Django 3.0.6 on 2020-09-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_auto_20200901_1855'),
        ('goods', '0024_auto_20200815_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='money.Period', verbose_name='Учетный период'),
        ),
    ]
