# Generated by Django 3.0.6 on 2020-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_invoice_task_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice_Task',
        ),
    ]
