# Generated by Django 3.0.6 on 2020-09-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_delete_invoice_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='goods.Invoice', verbose_name='Накладная'),
        ),
    ]
