# Generated by Django 3.0.6 on 2020-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_task_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
