# Generated by Django 3.0.6 on 2021-01-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_auto_20201007_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'brand', 'name']},
        ),
    ]
