# Generated by Django 3.0.6 on 2021-09-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0031_auto_20210124_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['-pk']},
        ),
    ]
